import type { Metadata } from "next";
import "./globals.css";
import { cacheLife } from "next/cache";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function testCache() {
    "use cache";
    cacheLife("default")
    const response = await fetch("https://soft98.ir");
   
    console.log(response);
  }
  testCache()
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
